joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

front_servo_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: "joint1"
  pid: {p: 100.0, i: 0.01, d: 10.0}

rear_servo_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: "joint1"
  pid: {p: 100.0, i: 0.01, d: 10.0}

rear_wheel_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "joint2"
  pid: {p: 100.0, i: 0.01, d: 10.0}

front_wheel_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "joint2"
  pid: {p: 100.0, i: 0.01, d: 10.0}